#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use CQ\CLI\CLI;
use CQ\Config\Config;

$config = new Config(__DIR__ . '/bootstrap');
$config->attach('app');

$cli = new CLI();

$cli->command('app:key', [new CQ\CLI\App(), 'key'])
    ->descriptions('Generate app key used for encryption');

$cli->run();
